### PR TITLE
Special characters in workspace name cause bugs

### LINKED ISSUE #34: Special characters in workspace name cause bugs
When giving workspaces names with special characters in them (e.g. `%` or `+`), they cause the workspace to break. For example:
- When you create a workspace with a name that contains `%` sign, then the site crashes. 
- When you give it a name like `test + test`, everything appears normal, but when you try to manually re-run the workspace, the workspace `test   test` will be the one running.

### PR DESCRIPTION
**Pull request by Mackofi**
Fixes #34.
The culprit was that we did not encode the URIs and I think I have fixed that in all places. I self tested these with these (` §'"+!%=(),.-~ˇ^˘°˛``˙´ `) special characters and all actions (create folder, create file, create workspace, and all of these nested) and they seemed to work fine, and I have not seen any crashes since.

### CODE REVIEW

**Comment by Mackofi** [comment]
Okay, `#` and `?` don't work yet. Looking into how to fix it.

File: lynxkite-app/web/src/Directory.tsx [hunk 1]
```diff
@@ -29,23 +29,53 @@ function EntryCreator(props: {
...
+      setError("Name cannot contain '/' characters");
+      return false;
+    }
+    if (name.trim() === "") {
+      setError("Name cannot be empty");
+      return false;
+    }
+    setError("");
+    return true;
+  }
```
Comment (darabos) [inline lynxkite-app/web/src/Directory.tsx:45]: Sounds good to me! I think this is in line with what Linux accepts as filename. (Linux also disallows the `null` character (`chr(0)`), but I don't think there's a risk of anyone typing that.)

File: lynxkite-app/web/src/Directory.tsx [hunk 2]
```diff
@@ -29,23 +29,53 @@ function EntryCreator(props: {
   onCreate: (name: string) => void;
 }) {
   const [isCreating, setIsCreating] = useState(false);
+  const [error, setError] = useState("");
```
Comment (darabos) [inline lynxkite-app/web/src/Directory.tsx:32]: There are many things that could have an error on this page. Since this is displayed for the naming of new workspaces/folders, I would give it a more specific name.

File: lynxkite-app/web/src/Directory.tsx [hunk 3]
```diff
@@ -67,13 +97,17 @@ export default function Directory() {
   const navigate = useNavigate();
 
   function link(item: DirectoryEntry) {
+    const encodedName = item.name
```
[the remark this answers is not in the document]
Comment (darabos) [reply lynxkite-app/web/src/Directory.tsx:102]: Agreed.

**Review by darabos — COMMENTED** [review]
Awesome, thanks a lot!

File: lynxkite-app/web/src/Directory.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (Mackofi) [reply lynxkite-app/web/src/Directory.tsx:102]: Done!

File: lynxkite-app/web/src/Directory.tsx (hunk 2 above)
Comment (Mackofi) [reply lynxkite-app/web/src/Directory.tsx:32]: Named it nameValidationError. Sounds descriptive to me.
